gem:
  # Add your `gem` command parameters here:
  #
  exclude:
    - rubocop
    - yard
    - yard-sorbet
    - rdoc
    - debug
    - language_server-protocol
    - rubocop-ast
    - rubocop-sorbet
    - bundler-audit
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
